# Generated by Django 2.2.13 on 2020-06-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20200623_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_learning_is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
