# Generated by Django 2.2.13 on 2020-06-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20200624_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_learning_is_creator',
            field=models.BooleanField(default=True),
        ),
    ]
