# Generated by Django 2.2.13 on 2020-06-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20200624_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_learning_is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
