# Generated by Django 2.2.13 on 2020-07-01 05:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(null=True, upload_to=sop.models.post_file_name)),
                ('publish', models.BooleanField(default=False)),
                ('creator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('textcontent', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('cover_type', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('cover_file', models.FileField(null=True, upload_to=sop.models.step_file_name)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sop.Post')),
            ],
        ),
        migrations.CreateModel(
            name='StepFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=sop.models.stepfile_file_name)),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sop.Step')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(null=True, upload_to=sop.models.course_file_name)),
                ('publish', models.BooleanField(default=False)),
                ('creator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(to='sop.Post')),
            ],
        ),
        migrations.CreateModel(
            name='SopHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sop.Post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'post_id')},
            },
        ),
    ]
