# Generated by Django 2.2.13 on 2020-06-23 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_role', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_name', models.CharField(default='', max_length=100)),
                ('grp_description', models.CharField(default='', max_length=250, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('user_joined', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_joined', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['grp_name'],
            },
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=100)),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_id', to='grouplearning.Group')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=100, unique=True)),
                ('course_description', models.CharField(default='', max_length=250, null=True)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='grouplearning.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='grp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grp_id', to='grouplearning.Group'),
        ),
    ]
