# Generated by Django 2.2.13 on 2020-07-01 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grouplearning.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sop', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grouplearning.Assignment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_description', models.CharField(blank=True, max_length=250, null=True)),
                ('group_image', models.ImageField(null=True, upload_to=grouplearning.models.group_image_upload)),
                ('default_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sop.Course')),
                ('user_joined', models.ManyToManyField(default='', related_name='user_joined', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='CommentStepReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grouplearning.CommentStep')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commentstep',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grouplearning.Group'),
        ),
        migrations.AddField(
            model_name='commentstep',
            name='step_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sop.Step'),
        ),
        migrations.AddField(
            model_name='commentstep',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommentGroupReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grouplearning.CommentGroup')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentGroupFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=grouplearning.models.comment_group_file_upload)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grouplearning.CommentGroup')),
            ],
        ),
        migrations.AddField(
            model_name='commentgroup',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grouplearning.Group'),
        ),
        migrations.AddField(
            model_name='commentgroup',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssignmentWorkFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=grouplearning.models.assignment_work_file_upload)),
                ('assignment_work_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grouplearning.AssignmentWork')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=grouplearning.models.assignment_file_upload)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grouplearning.Assignment')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grouplearning.Group'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
