# Generated by Django 2.2.13 on 2020-06-23 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grouplearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='course_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='grouplearning.Course'),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='group_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_id', to='grouplearning.Group'),
        ),
    ]
