# Generated by Django 2.2.13 on 2020-07-01 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grouplearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creator_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
