# Generated by Django 2.2.13 on 2020-07-01 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grouplearning', '0002_group_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='default_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sop.Course'),
        ),
    ]
