# Generated by Django 2.2.13 on 2020-06-23 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grouplearning.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grouplearning', '0002_auto_20200623_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdo_name', models.CharField(default='', max_length=100, unique=True)),
                ('vdo_file', models.FileField(null=True, upload_to=grouplearning.models.course_file_upload)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='image',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='course_image',
            field=models.ImageField(null=True, upload_to=grouplearning.models.course_image_upload),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='grp_image',
            field=models.ImageField(null=True, upload_to=grouplearning.models.group_image_upload),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='vdo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vdo_id', to='grouplearning.Video'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(blank=True, default='', max_length=100)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grouplearning.Course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'unique_together': {('user', 'course_id')},
            },
        ),
    ]
