# Generated by Django 2.2.13 on 2020-06-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grouplearning', '0004_group_creator_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['group_name']},
        ),
        migrations.RenameField(
            model_name='group',
            old_name='grp_description',
            new_name='group_description',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='grp_image',
            new_name='group_image',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='grp_name',
            new_name='group_name',
        ),
    ]
