# Generated by Django 2.2.13 on 2020-06-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouplearning', '0005_auto_20200624_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
    ]
